#+title: Brainstorming Word Vomit
#+author: L;S RisingSunfish

* Premise
SashAnne kitchen sex, with a planned Marcy interruption.

* Draft 1
Anne finished washing the dishes and removed her gloves. They had a
dishwasher, but she found the act of hand washing them to be relaxing.

Anne heard footsteps approaching from behind and let Sasha wrap her arms around
her waist. She reached back and turned her head to kiss her wife.

"You all done?" Sasha asked after she pulled away.

"Yep. All done." Anne said.

She turned around and smiled, then planted another kiss on Sasha's lips,
one that lasted longer than the one before it. Sasha opened her mouth
when their lips met, and Anne quickly reciprocated. Their make-out
session was brief, though.

Anne pulled away and said, "/Somebody's/ hot and bothered.", and chuckled.

Sasha smiled and rolled her eyes. "Yes, Anne. I've been waiting since
you got home.", she said, then grabbed Anne's ass, pulling her in
closer. "Now, would my lovely wife be so kind as to fuck the shit out
of me?"

Anne laughed and removed Sasha's hands from her ass, and firmly wrapped
gripped her wrists, holding them up by her head. "Oh, you'd like than
now, wouldn't you, Sashy? Well, the way /I/ see it, /I'm/ the one who
made dinner, and /I'm/ the one who just finished washing the dishes."

"Hey, I offered to load the dishwasher!" Sasha said in feigned protest.

"Fair point." Anne said, then pulled her face up to Sasha's "Still, if
you want mama to fuck the shit out of you that badly, you're gonna need
to make sure she feels appreciated for all of the /other/ stuff she's
done for you. Okay?"

Sasha smiled and bit her lip, then moaned, "Mhmm~" with a nod.

Anne chuckled and said, "Good girl~", then pressed her lips into her
wife's, and let go of her wrists. She wrapped one arm around Sasha's
back and pulled her in close. Sasha moaned into Anne's mouth as she was
pulled close, and their tongues caressed one another.

Anne bit and sucked on Sasha's lower lip as she pulled away from the
kiss. "Alright now, enough of that. Knees. /Now/." She commanded,
snapping and pointing at the ground.

Sasha grinned as she lifted her got down to her knees and watched her
wife remove her shorts. Anne had a bush, but she kept it trimmed, which
Sasha liked. Without missing a beat, Anne grabbed Sasha's head and
shoved her nose /directly/ into that bush, which she /loved/.

Sasha breathed in the musky scent of Anne's slightly sweat soaked pubes,
then opened her mouth and quickly got to work pleasing her mistress. She
wasn't into the whole 'mama' thing like Anne and Marcy were, and greatly
preferred to think of her as a /mistresses/, but she wasn't turned off
by it. As long as they made it clear that they were the one in charge,
Sasha didn't care /what/ they called her or themselves.

Before long, Anne was quickly grinding into Sasha's face, causing her
prickly bush against her lips. Sasha breathed in her wife's powerful
musk while she worked with her tongue.

Anne's phone rang, causing her to jump and let go of Sasha's head, but
Sasha had wrapped her hands around and had a firm grip on Anne's rear,
and was able to continue working. Then she casually picked up Anne's
shorts and handed them to her.

Anne fished through her pockets for her phone, saw that it was Marcy,
then answered. "H-hey Marcy w-what's up. Ah~", she said, trying and
failing to hide what was happening.

"Havin' a good time there, Anna Banana~" Marcy said, with a tone that
very much indicated that they knew /exactly/ what was happening.

"Uhm- /Fuck/- Y-yeah, I guess you could s-/say/ that~" Anne struggled to
get the words out while Sasha munched on her cunt. Sasha was /really/
good at eating pussy, which should be expected from someone who enjoyed
it as much as she did.

"That's good~ Why don't you turn on your camera so mama can see how her
babies are doin'~"

~~~

Marcy leaned back and watched their desktop monitor with one slowly
gently rubbing her clit.

"Oh, uhm... Yes /mother/, I could do that for you..." Anne said. Seconds
later, the video appeared on her their screen, replacing the two profile
pictures that they was looking at before. The audio also changed as Anne
switched into speaker mode.

"Good girl~" they said. They had an excellent view of Sasha's head
buried in Anne's pussy with her eyes closed. They was very pleased to
see them playing together like this, and had a massive grin on their
face.

"Th-thank you mother~" Anne moaned.

"You too Sashy! You look like you're being a /very/ good girl to your
big sister~" Marcy cooed.

Sasha let out a 'thank you' hum as she continued working.

Marcy smiled and continued rubbing theirself while their other hand
kneaded a nippleless breast.

~~~

"How close is my banana baby~" Marcy said.

Anne's other hand was on the back of Sasha's head, and she'd
started grinding into her face again. "V-very close mmmotherrr~" she
said, and shuddered. She let go of Sasha's head and put her hand on the
counter for support as her legs trembled.

Anne heard a satisfied hum from Marcy on the other end as she climaxed.
She looked down at Sasha, who now looked up at her with a smug grin.

Sasha stood up a wiped her mouth while Anne rolled her eyes. "Now will
by adorably sexy mistress-wife please fuck me?" she asked, then
kissed her.

Anne softly moaned into the kiss before pulling away and smiling. "Well,
when you ask like that, how could mama refuse~" she said, then picked
Sasha up, seating her on the counter. She also handed Sasha her phone so
she could show Marcy what she was doing.

Anne smiled up at Sasha as she got down on her knees and lifted Sasha's
dress. Sasha bit her lip in anticipation, then heard Marcy's voice
through the phone, "Sashy, what do you say to your big sister?"

"Thank you mistress Anne~" she replied.

"You're very welcome~" Anne said, then buried her face in Sasha's
clean-shaven cunt. While she wasn't as good at giving head as her wife,
her hands more than made up for it. She worked both her tongue and her
fingers on Sasha's soaked pussy, and had her panting in seconds.

It didn't take much for Sasha to get off, but that just meant that she
could do it more. Within a minute she had crossed her legs behind
Anne's head and shuddered in orgasm. Anne did not let up. She was going
to ensure that Sasha /needed/ to be carried to bed.

~~~

"You're such good girls~" Marcy said between heavy breaths as they began
to approach their own climax.

"Th-thank you m-m-mistress~~" Sasha replied, struggling to speak through
another orgasm.

Marcy watched Anne munch on Sasha's pussy as they massaged their own
clit. /She's so fucking hot/ they thought. They'd be visiting the girls
in a few weeks, and the wait was hell.

Marcy had yet to tell them about their newfound bladder control fetish;
they wanted to tell them in person. In the mean time, they rubbed their
clit through her panties with a full bladder. They didn't often wear
panties, but something about soaking a pair a panties in their piss was
so hot. More often than not, when they /did/ wear them, /this/ was the
reason.

Marcy's toes curled, and their back arched in their chair as they came
to climax, and at the same time, finally opened the floodgates. They'd
gotten quite good at holding; they hadn't used the bathroom since that
morning, and had downed at least two liters of water since then.

The pleasure of the climax mixed with the relief of finally letting
themself pee was euphoric. Their panties were quickly soaked, and then
the pee pad they was sat on was quickly saturated as well.
