#+title: Brainstorming Word Vomit
#+author: L;S RisingSunfish

* Premise
Anne eats Sasha's pussy on the kitchen counter.

* Here we go bois
Anne finished washing the dishes and removed her gloves. They had a
dishwasher, but she found the act of hand washing them to be relaxing.

Anne heard footsteps approaching from behind and let Sasha wrap her arms around
her waist. She reached back and turned her head to kiss her wife.

"You all done?" Sasha asked after she pulled away.

"Yep. All done." Anne said.

She turned around and smiled, then planted another kiss on Sasha's lips,
one that lasted longer than the one before it. Sasha opened her mouth
when their lips met, and Anne quickly reciprocated. Their make-out
session was brief, though.

Anne pulled away and said, "/Somebody's/ hot and bothered.", and chuckled.

Sasha smiled and rolled her eyes. "Yes, Anne. I've been waiting since
you got home.", she said, then grabbed Anne's ass, pulling her in
closer. "Now, would my lovely wife be so kind as to fuck the shit out
of me?"

Anne laughed and removed Sasha's hands from her ass, and firmly wrapped
gripped her wrists, holding them up by her head. "Oh, you'd like than
now, wouldn't you, Sashy? Well, the way /I/ see it, /I'm/ the one who
made dinner, and /I'm/ the one who just finished washing the dishes."

"Hey, I offered to load the dishwasher!" Sasha said in feigned protest.

"Fair point." Anne said, then pulled her face up to Sasha's "Still, if
you want mama to fuck the shit out of you that badly, you're gonna need
to make sure she feels appreciated for all of the /other/ stuff she's
done for you. Okay?"

Sasha smiled and bit her lip, then moaned, "Mhmm~" with a nod.

Anne chuckled and said, "Good girl~", then pressed her lips into her
wife's, and let go of her wrists. She wrapped one arm around Sasha's
back and pulled her in close. Sasha moaned into Anne's mouth as she was
pulled close, and their tongues caressed one another.
